version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: jobtracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jobtracker
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - jobtracker-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Web Interface (like MongoDB Compass)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: jobtracker-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jobtracker-network

  # JobTracker Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jobtracker-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://RohithB:selvi2010@mongodb:27017/jobtracker?authSource=admin
      PORT: 5000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jobtracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  jobtracker-network:
    driver: bridge