version: '3.8'

services:
  # MongoDB Database for Development
  mongodb:
    image: mongo:7.0
    container_name: jobtracker-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jobtracker
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - jobtracker-dev-network

  # MongoDB Web Interface for Development
  mongo-express:
    image: mongo-express:1.0.0
    container_name: jobtracker-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: RohithB
      ME_CONFIG_MONGODB_ADMINPASSWORD: selvi2010
      ME_CONFIG_MONGODB_URL: mongodb://RohithB:selvi2010`@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      - mongodb
    networks:
      - jobtracker-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  jobtracker-dev-network:
    driver: bridge