version: '3.8'

services:
  # JobTracker App
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jobtracker-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URL: ${MONGODB_URL}
      PORT: ${PORT}
    networks:
      - jobtracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jobtracker-network:
    driver: bridge